import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "es" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    // ============= NAVBAR =============
    "nav.home": "Inicio",
    "nav.fleet": "Flota",
    "nav.experiences": "Experiencias",
    "nav.routes": "Rutas",
    "nav.about": "Nosotros",
    "nav.bookNow": "Reserva Ya",
    "nav.changeLanguage": "Cambiar idioma",

    // ============= INDEX PAGE =============
    "hero.title1": "El Mediterráneo,",
    "hero.title2": "como nunca lo has vivido.",
    "hero.subtitle": "Experiencias náuticas exclusivas en el corazón de la Costa Blanca",
    "hero.cta": "Ver Flota",
    "index.verFlota": "Ver la Flota",
    "index.descubrirBarcos": "Descubrir barcos",
    "index.experiencias": "Experiencias Únicas",
    "index.verRutas": "Ver rutas y eventos",
    "index.contacto": "Contacta Directo",
    "index.whatsapp": "Habla por WhatsApp",
    "index.whyTitle": "¿Por qué Golden Coast Charter?",
    "index.whyItem1Title": "Experiencia y Tradición",
    "index.whyItem1Desc": "Más de 10 años navegando la Costa Blanca, con patrones que conocen cada cala secreta y la historia del Mediterráneo.",
    "index.whyItem2Title": "Calidad y Excelencia",
    "index.whyItem2Desc": "Flota propia mantenida a la perfección. Cada detalle, desde la limpieza hasta el equipamiento, está pensado para una experiencia de 5 estrellas.",
    "index.whyItem3Title": "Seguridad y Confianza",
    "index.whyItem3Desc": "Tu tranquilidad es nuestra prioridad. Todos nuestros barcos cuentan con las máximas certificaciones de seguridad, seguros a todo riesgo y el mejor equipo.",
    "index.ctaTitle": "¿Listo para zarpar?",
    "index.ctaSubtitle": "Reserva tu experiencia náutica exclusiva en la Costa Blanca",
    "index.ctaButton": "Solicitar Presupuesto",

    // ============= FLEET PAGE =============
    "fleet.heroTitle": "Nuestra",
    "fleet.heroHighlight": "Flota",
    "fleet.heroDesc": "Barcos de motor y vela cuidadosamente seleccionados para ofrecerte la mejor experiencia en el Mediterráneo.",
    "fleet.scrollHint": "Desliza horizontalmente para explorar nuestra flota",
    "fleet.type.motor": "Motor",
    "fleet.type.sail": "Vela",
    "fleet.capacity": "Hasta {count} personas",
    "fleet.withCaptain": "Con patrón",
    "fleet.withoutCaptain": "Sin patrón disponible",
    "fleet.features": "Comodidades incluidas:",
    "fleet.priceLabel": "Precio orientativo",
    "fleet.from": "desde",
    "fleet.perDay": "/día",
    "fleet.checkAvailability": "Consultar Disponibilidad",
    "fleet.notFound.title": "¿No encuentras lo que buscas?",
    "fleet.notFound.desc": "Tenemos más opciones disponibles y podemos personalizar cualquier experiencia según tus necesidades. Contáctanos y te ayudaremos a encontrar el barco perfecto.",
    "fleet.notFound.button": "Contactar por WhatsApp",
    "fleet.azure.desc": "Elegante yate a motor perfecto para celebraciones y rutas rápidas por la costa",
    "fleet.mediterranean.desc": "Velero ideal para experiencias náuticas auténticas y relajantes",
    "fleet.golden.desc": "Motor yacht versátil para grupos, familias y puestas de sol románticas",
    "fleet.serenity.desc": "Velero clásico ideal para puestas de sol románticas y explorar calas escondidas por la costa",
    "fleet.adrenaline.desc": "Lancha rápida y potente para los que buscan aventura. Perfecta para deportes acuáticos y rutas rápidas",
    "fleet.familia.desc": "Catamarán estable y espacioso diseñado para salidas familiares. Una plataforma perfecta para disfrutar del mar",
    "fleet.feature.bathroom": "Baño completo",
    "fleet.feature.solarium": "Solárium",
    "fleet.feature.fridge": "Nevera",
    "fleet.feature.music": "Equipo de música",
    "fleet.feature.lifejackets": "Chalecos salvavidas",
    "fleet.feature.cabin": "Cabina doble",
    "fleet.feature.kitchen": "Cocina equipada",
    "fleet.feature.shower": "Ducha",
    "fleet.feature.gps": "GPS y navegación",
    "fleet.feature.shade": "Zona de sombra",
    "fleet.feature.platform": "Plataforma de baño",
    "fleet.feature.bluetooth": "Altavoces Bluetooth",
    "fleet.feature.snorkel": "Snorkel incluido",
    "fleet.feature.paddleboard": "Paddleboard",
    "fleet.feature.snorkelKit": "Equipo de snorkel",

    // ============= EXPERIENCES PAGE =============
    "exp.heroTitle": "Experiencias",
    "exp.heroHighlight": "Inolvidables",
    "exp.heroDesc": "Cada navegación es única. Crea recuerdos que durarán para siempre en las aguas más hermosas del Mediterráneo.",
    "exp.includes": "Incluye:",
    "exp.idealFor": "Ideal para:",
    "exp.requestInfo": "Solicitar Info",
    "exp.sunset.title": "Puestas de Sol Románticas",
    "exp.sunset.desc": "Vive la magia del atardecer mediterráneo desde la cubierta de un barco. Incluye copa de cava, música ambiente y los mejores puntos de vista de la Costa Blanca.",
    "exp.sunset.highlight1": "2-3 horas de navegación",
    "exp.sunset.highlight2": "Copa de bienvenida",
    "exp.sunset.highlight3": "Música personalizada",
    "exp.sunset.highlight4": "Snacks gourmet",
    "exp.sunset.price": "desde 450€",
    "exp.sunset.ideal": "Parejas, aniversarios, peticiones de mano",
    "exp.celebrations.title": "Despedidas y Cumpleaños",
    "exp.celebrations.desc": "Celebra tus momentos especiales navegando por las aguas cristalinas. Packs personalizados con decoración, catering, música y actividades acuáticas.",
    "exp.celebrations.highlight1": "Decoración temática",
    "exp.celebrations.highlight2": "Catering a medida",
    "exp.celebrations.highlight3": "Sistema de sonido profesional",
    "exp.celebrations.highlight4": "Actividades incluidas",
    "exp.celebrations.price": "desde 800€",
    "exp.celebrations.ideal": "Grupos de amigos, despedidas, cumpleaños",
    "exp.family.title": "Aventuras Familiares",
    "exp.family.desc": "Rutas diseñadas para disfrutar en familia, con paradas en calas secretas, snorkel, paddle surf y pesca. Seguridad total y diversión garantizada para todas las edades.",
    "exp.family.highlight1": "Equipo de snorkel",
    "exp.family.highlight2": "Paddle surf",
    "exp.family.highlight3": "Zonas de sombra",
    "exp.family.highlight4": "Seguridad infantil",
    "exp.family.price": "desde 600€",
    "exp.family.ideal": "Familias con niños, grupos multigeneracionales",
    "exp.custom.title": "Excursiones a Medida",
    "exp.custom.desc": "Diseñamos la experiencia perfecta según tus preferencias: rutas gastronómicas, yoga en el mar, fotografía profesional, eventos corporativos o lo que imagines.",
    "exp.custom.highlight1": "Totalmente personalizable",
    "exp.custom.highlight2": "Rutas exclusivas",
    "exp.custom.highlight3": "Servicios premium",
    "exp.custom.highlight4": "Atención VIP",
    "exp.custom.price": "Presupuesto personalizado",
    "exp.custom.ideal": "Cualquier ocasión especial",
    "exp.cta.title": "¿Tienes una idea especial en mente?",
    "exp.cta.desc": "Creamos experiencias completamente personalizadas. Cuéntanos tu visión y la haremos realidad.",
    "exp.cta.button": "Crear Mi Experiencia",

    // ============= ABOUT PAGE =============
    "about.heroTitle": "Sobre",
    "about.heroHighlight": "Nosotros",
    "about.heroDesc": "Somos un equipo de apasionados por el mar con más de 10 años creando experiencias náuticas únicas en la Costa Blanca.",
    "about.story.title": "Nuestra Historia",
    "about.story.p1": "Golden Coast Charter nace de una decisión clara: vivir del mar y crear algo propio.",
    "about.story.p2": "Con más de una década de experiencia navegando por la Costa Blanca, trabajando en puertos y formando a personas como monitor de vela, piragua y remo, el mar dejó de ser solo una afición para convertirse en un proyecto profesional.",
    "about.story.p3": "Con titulaciones como PER y Patrón de Yate, decidí dar el paso y crear una empresa diferente. No una gran corporación sin rostro, sino un proyecto personal, cuidado y cercano.",
    "about.story.p4": "Golden Coast Charter no nace de una inversión. Nace de años de mar, aprendizaje y ambición.",
    "about.story.p5": "Operamos desde Dénia y Jávea ofreciendo experiencias adaptadas a cada cliente: desde escapadas relajadas hasta celebraciones especiales o jornadas de aventura.",
    "about.story.p6": "Cada salida está pensada con un objetivo claro: que disfrutes sin preocuparte de nada.",
    "about.story.p7": "Porque aquí no solo alquilamos barcos. Creamos momentos que se recuerdan.",
    "about.values.title": "Nuestros Valores",
    "about.value1.title": "Pasión por el Mar",
    "about.value1.desc": "Cada salida es una oportunidad para compartir nuestra pasión por la navegación y el Mediterráneo.",
    "about.value2.title": "Seguridad Primero",
    "about.value2.desc": "Todos nuestros barcos cuentan con certificaciones al día, seguros completos y equipamiento de seguridad profesional.",
    "about.value3.title": "Excelencia en Servicio",
    "about.value3.desc": "Nuestro objetivo es superar tus expectativas en cada experiencia, cuidando cada detalle.",
    "about.value4.title": "Trato Personalizado",
    "about.value4.desc": "No somos una gran corporación. Somos un equipo que te acompaña desde la reserva hasta el desembarque.",
    "about.certs.title": "Certificados y Licencias",
    "about.certs.subtitle": "Tu seguridad y tranquilidad son nuestra prioridad",
    "about.cert1": "Licencias náuticas profesionales",
    "about.cert2": "Seguros todo riesgo",
    "about.cert3": "Certificados de navegabilidad",
    "about.cert4": "Formación en primeros auxilios",
    "about.cert5": "Mantenimiento certificado",
    "about.certs.footer": "Todos nuestros patrones cuentan con titulación profesional y años de experiencia navegando en estas aguas.",
    "about.testimonials.title": "Lo Que Dicen Nuestros Clientes",
    "about.testimonials.subtitle": "Experiencias reales de personas que navegaron con nosotros",
    "about.test1.name": "María González",
    "about.test1.location": "Madrid",
    "about.test1.text": "Una experiencia inolvidable. El atardecer desde el barco fue mágico y el equipo súper profesional y atento. ¡Totalmente recomendable!",
    "about.test2.name": "John Smith",
    "about.test2.location": "UK",
    "about.test2.text": "Best boat charter experience in Costa Blanca! Beautiful yacht, amazing crew, and the hidden coves were spectacular. Will definitely return!",
    "about.test3.name": "Carlos Ruiz",
    "about.test3.location": "Valencia",
    "about.test3.text": "Celebramos mi cumpleaños a bordo y fue perfecto. La decoración, la comida, todo estaba cuidado al detalle. Gracias por hacer este día tan especial.",
    "about.cta.title": "¿Listo para tu aventura en el mar?",
    "about.cta.subtitle": "Únete a cientos de clientes satisfechos que ya han vivido la experiencia Golden Coast",
    "about.cta.button": "Solicita tu Presupuesto",

    // ============= BOOKING PAGE =============
    "booking.heroTitle": "Solicita tu",
    "booking.heroHighlight": "Presupuesto",
    "booking.heroDesc": "Completa el formulario y te enviaremos un presupuesto personalizado. También puedes contactarnos directamente por WhatsApp para una respuesta inmediata.",
    "booking.form.name": "Nombre completo",
    "booking.form.email": "Email",
    "booking.form.phone": "Teléfono",
    "booking.form.date": "Fecha preferida",
    "booking.form.guests": "Número de personas",
    "booking.form.guestsPlaceholder": "Ej: 8",
    "booking.form.boatType": "Tipo de barco",
    "booking.form.selectBoat": "Selecciona...",
    "booking.form.experience": "Experiencia deseada",
    "booking.form.message": "Mensaje adicional",
    "booking.form.messagePlaceholder": "Cuéntanos más sobre lo que buscas...",
    "booking.form.submit": "Enviar Solicitud",
    "booking.form.sending": "Enviando...",
    "booking.form.privacy": "Al enviar este formulario aceptas nuestra política de privacidad",
    "booking.form.namePlaceholder": "Tu nombre",
    "booking.form.emailPlaceholder": "tu@email.com",
    "booking.form.phonePlaceholder": "+34 676 26 26 28",
    "booking.boat.motor": "Motor (con patrón)",
    "booking.boat.sailWith": "Vela (con patrón)",
    "booking.boat.sailWithout": "Vela (sin patrón)",
    "booking.boat.any": "Cualquiera",
    "booking.exp.sunset": "Puesta de sol",
    "booking.exp.party": "Despedida/Cumpleaños",
    "booking.exp.family": "Aventura familiar",
    "booking.exp.custom": "Personalizada",
    "booking.exp.other": "Otra",
    "booking.benefits.title": "¿Por qué reservar con nosotros?",
    "booking.benefit1": "Respuesta en menos de 24h",
    "booking.benefit2": "Presupuesto sin compromiso",
    "booking.benefit3": "Asesoramiento personalizado",
    "booking.benefit4": "Flexibilidad de fechas",
    "booking.contact.title": "¿Prefieres contacto directo?",
    "booking.contact.whatsapp": "WhatsApp directo",
    "booking.contact.phone": "+34 676 26 26 28",
    "booking.contact.email": "Email",
    "booking.contact.schedule": "Horario: Lun-Dom 9:00-21:00",
    "booking.toast.error.title": "Error",
    "booking.toast.error.desc": "Por favor completa todos los campos obligatorios",
    "booking.toast.success.title": "¡Solicitud enviada!",
    "booking.toast.success.desc": "Nos pondremos en contacto contigo en menos de 24 horas.",

    // ============= ROUTES PAGE =============
    "routes.heroTitle": "Nuestras",
    "routes.heroHighlight": "Rutas",
    "routes.heroDesc": "Descubre los rincones más espectaculares de la Costa Blanca. Cada ruta es una aventura única diseñada para vivir el Mediterráneo en su máxima expresión.",
    "routes.route1.name": "Las Rotas & Reserva Marina del Cabo de San Antonio",
    "routes.route1.location": "Dénia - Cabo San Antonio",
    "routes.route1.duration": "4-6 horas",
    "routes.route1.desc": "Navega por la impresionante costa de Las Rotas, descubriendo sus cuevas escondidas y haciendo snorkel en las aguas protegidas de la reserva marina del Cabo de San Antonio. Un viaje al corazón de la naturaleza.",
    "routes.route1.highlight1": "Cuevas naturales",
    "routes.route1.highlight2": "Snorkel en reserva marina",
    "routes.route1.highlight3": "Aguas cristalinas",
    "routes.route1.highlight4": "Fondos rocosos",
    "routes.route2.name": "Las Calas de Jávea (Granadella, Portitxol, Ambolo)",
    "routes.route2.location": "Jávea - Costa del Cabo",
    "routes.route2.duration": "5-7 horas",
    "routes.route2.desc": "Explora las calas más famosas de Jávea desde una perspectiva única. Fondea en las aguas turquesas de Granadella, admira las casitas de cúpulas azules de Portitxol y siente la magia de Ambolo.",
    "routes.route2.highlight1": "Cala Granadella",
    "routes.route2.highlight2": "Portitxol",
    "routes.route2.highlight3": "Cala Ambolo",
    "routes.route2.highlight4": "Fondeo en calas vírgenes",
    "routes.route3.name": "Atardecer y Acantilados del Montgó",
    "routes.route3.location": "Dénia - Montgó",
    "routes.route3.duration": "2-3 horas",
    "routes.route3.desc": "Vive un atardecer inolvidable mientras el sol se oculta tras la majestuosa montaña del Montgó. Un momento de pura magia, perfecto para una velada romántica o un cierre de día en paz.",
    "routes.route3.highlight1": "Atardecer mágico",
    "routes.route3.highlight2": "Vistas del Montgó",
    "routes.route3.highlight3": "Momento romántico",
    "routes.route3.highlight4": "Cava incluido",
    "routes.highlights": "Destacados de la ruta:",
    "routes.bookRoute": "Reservar esta Ruta",
    "routes.cta.title": "¿Tienes una ruta en mente?",
    "routes.cta.desc": "Podemos personalizar cualquier itinerario según tus preferencias. Ya sea una cala específica, una combinación de rutas, o un destino especial, diseñamos la experiencia perfecta para ti.",
    "routes.cta.button": "Crear Ruta Personalizada",

    // ============= FOOTER =============
    "footer.slogan": "Experiencias náuticas en la Costa Blanca. Alquiler de barcos en Dénia y Jávea para momentos inolvidables.",
    "footer.quickLinks": "Enlaces Rápidos",
    "footer.experiences": "Experiencias",
    "footer.contact": "Contacto",
    "footer.email": "Email",
    "footer.phone": "Teléfono",
    "footer.social": "Síguenos",
    "footer.rights": "Todos los derechos reservados",
    "footer.legal.privacy": "Política de Privacidad",
    "footer.legal.terms": "Términos y Condiciones",
    "footer.legal.cookies": "Cookies",
    "footer.legal.notice": "Aviso Legal",
    "footer.exp.sunset": "Puestas de Sol",
    "footer.exp.celebrations": "Celebraciones",
    "footer.exp.family": "Rutas Familiares",
    "footer.exp.custom": "Charter Personalizado",
    "footer.location": "Puerto de Dénia\nMarina de Jávea\nCosta Blanca, España",
  },
  en: {
    // ============= NAVBAR =============
    "nav.home": "Home",
    "nav.fleet": "Fleet",
    "nav.experiences": "Experiences",
    "nav.routes": "Routes",
    "nav.about": "About Us",
    "nav.bookNow": "Book Now",
    "nav.changeLanguage": "Change language",

    // ============= INDEX PAGE =============
    "hero.title1": "The Mediterranean,",
    "hero.title2": "like you've never experienced it.",
    "hero.subtitle": "Exclusive nautical experiences in the heart of Costa Blanca",
    "hero.cta": "View Fleet",
    "index.verFlota": "View Fleet",
    "index.descubrirBarcos": "Discover boats",
    "index.experiencias": "Unique Experiences",
    "index.verRutas": "View routes and events",
    "index.contacto": "Direct Contact",
    "index.whatsapp": "Chat on WhatsApp",
    "index.whyTitle": "Why Golden Coast Charter?",
    "index.whyItem1Title": "Experience and Tradition",
    "index.whyItem1Desc": "Over 10 years sailing the Costa Blanca, with captains who know every secret cove and Mediterranean history.",
    "index.whyItem2Title": "Quality and Excellence",
    "index.whyItem2Desc": "Our own fleet maintained to perfection. Every detail, from cleanliness to equipment, is designed for a 5-star experience.",
    "index.whyItem3Title": "Safety and Trust",
    "index.whyItem3Desc": "Your peace of mind is our priority. All our boats have the highest safety certifications, comprehensive insurance, and the best equipment.",
    "index.ctaTitle": "Ready to set sail?",
    "index.ctaSubtitle": "Book your exclusive nautical experience in Costa Blanca",
    "index.ctaButton": "Request Quote",

    // ============= FLEET PAGE =============
    "fleet.heroTitle": "Our",
    "fleet.heroHighlight": "Fleet",
    "fleet.heroDesc": "Carefully selected motor and sailboats to offer you the best experience in the Mediterranean.",
    "fleet.scrollHint": "Swipe horizontally to explore our fleet",
    "fleet.type.motor": "Motor",
    "fleet.type.sail": "Sail",
    "fleet.capacity": "Up to {count} people",
    "fleet.withCaptain": "With Captain",
    "fleet.withoutCaptain": "Without captain available",
    "fleet.features": "Included amenities:",
    "fleet.priceLabel": "Estimated price",
    "fleet.from": "from",
    "fleet.perDay": "/day",
    "fleet.checkAvailability": "Check Availability",
    "fleet.notFound.title": "Can't find what you're looking for?",
    "fleet.notFound.desc": "We have more options available and can customize any experience according to your needs. Contact us and we'll help you find the perfect boat.",
    "fleet.notFound.button": "Contact via WhatsApp",
    "fleet.azure.desc": "Elegant motor yacht perfect for celebrations and fast coastal routes",
    "fleet.mediterranean.desc": "Luxury sailboat ideal for authentic and relaxing nautical experiences",
    "fleet.golden.desc": "Versatile motor yacht for groups, families and romantic sunsets",
    "fleet.serenity.desc": "Classic sailboat ideal for romantic sunsets and exploring hidden coves along the coast",
    "fleet.adrenaline.desc": "Fast and powerful speedboat for those seeking adventure. Perfect for water sports and quick routes",
    "fleet.familia.desc": "Stable and spacious catamaran designed for family outings. A perfect platform to enjoy the sea",
    "fleet.feature.bathroom": "Full bathroom",
    "fleet.feature.solarium": "Solarium",
    "fleet.feature.fridge": "Fridge",
    "fleet.feature.music": "Music system",
    "fleet.feature.lifejackets": "Life jackets",
    "fleet.feature.cabin": "Double cabin",
    "fleet.feature.kitchen": "Equipped kitchen",
    "fleet.feature.shower": "Shower",
    "fleet.feature.gps": "GPS and navigation",
    "fleet.feature.shade": "Shade area",
    "fleet.feature.platform": "Swimming platform",
    "fleet.feature.bluetooth": "Bluetooth speakers",
    "fleet.feature.snorkel": "Snorkel included",
    "fleet.feature.paddleboard": "Paddleboard",
    "fleet.feature.snorkelKit": "Snorkel equipment",

    // ============= EXPERIENCES PAGE =============
    "exp.heroTitle": "Experiences",
    "exp.heroHighlight": "Unforgettable",
    "exp.heroDesc": "Every sail is unique. Create memories that will last forever in the most beautiful Mediterranean waters.",
    "exp.includes": "Includes:",
    "exp.idealFor": "Ideal for:",
    "exp.requestInfo": "Request Info",
    "exp.sunset.title": "Romantic Sunsets",
    "exp.sunset.desc": "Experience the magic of the Mediterranean sunset from the deck of a luxury boat. Includes cava, ambient music and the best views of the Costa Blanca.",
    "exp.sunset.highlight1": "2-3 hours sailing",
    "exp.sunset.highlight2": "Welcome drink",
    "exp.sunset.highlight3": "Personalized music",
    "exp.sunset.highlight4": "Gourmet snacks",
    "exp.sunset.price": "from 450€",
    "exp.sunset.ideal": "Couples, anniversaries, marriage proposals",
    "exp.celebrations.title": "Parties & Birthdays",
    "exp.celebrations.desc": "Celebrate your special moments sailing through crystal-clear waters. Customized packages with decoration, catering, music and water activities.",
    "exp.celebrations.highlight1": "Themed decoration",
    "exp.celebrations.highlight2": "Custom catering",
    "exp.celebrations.highlight3": "Professional sound system",
    "exp.celebrations.highlight4": "Activities included",
    "exp.celebrations.price": "from 800€",
    "exp.celebrations.ideal": "Friend groups, bachelor parties, birthdays",
    "exp.family.title": "Family Adventures",
    "exp.family.desc": "Routes designed for family enjoyment, with stops at secret coves, snorkeling, paddle surfing and fishing. Total safety and guaranteed fun for all ages.",
    "exp.family.highlight1": "Snorkel equipment",
    "exp.family.highlight2": "Paddle surf",
    "exp.family.highlight3": "Shade areas",
    "exp.family.highlight4": "Child safety",
    "exp.family.price": "from 600€",
    "exp.family.ideal": "Families with children, multigenerational groups",
    "exp.custom.title": "Custom Excursions",
    "exp.custom.desc": "We design the perfect experience according to your preferences: gastronomic routes, sea yoga, professional photography, corporate events or whatever you imagine.",
    "exp.custom.highlight1": "Fully customizable",
    "exp.custom.highlight2": "Exclusive routes",
    "exp.custom.highlight3": "Premium services",
    "exp.custom.highlight4": "VIP attention",
    "exp.custom.price": "Custom quote",
    "exp.custom.ideal": "Any special occasion",
    "exp.cta.title": "Have a special idea in mind?",
    "exp.cta.desc": "We create completely customized experiences. Tell us your vision and we'll make it happen.",
    "exp.cta.button": "Create My Experience",

    // ============= ABOUT PAGE =============
    "about.heroTitle": "About",
    "about.heroHighlight": "Us",
    "about.heroDesc": "We are a team passionate about the sea with over 10 years creating unique nautical experiences on the Costa Blanca.",
    "about.story.title": "Our Story",
    "about.story.p1": "Golden Coast Charter was born from a clear decision: to live by the sea and build something of our own.",
    "about.story.p2": "With over a decade of experience sailing the Costa Blanca, working in ports, and training people as a sailing, kayaking, and rowing instructor, the sea stopped being just a hobby and became a professional project.",
    "about.story.p3": "With qualifications such as PER and Yacht Skipper, I decided to take the leap and create a different kind of company. Not a faceless corporation, but a personal, careful, and close project.",
    "about.story.p4": "Golden Coast Charter is not born from an investment. It is born from years of sea, learning, and ambition.",
    "about.story.p5": "We operate from Dénia and Jávea offering experiences tailored to each client: from relaxed getaways to special celebrations or adventure days.",
    "about.story.p6": "Every trip is designed with a clear goal: for you to enjoy yourself without worrying about a thing.",
    "about.story.p7": "Because here we don't just rent boats. We create moments to remember.",
    "about.values.title": "Our Values",
    "about.value1.title": "Passion for the Sea",
    "about.value1.desc": "Every outing is an opportunity to share our passion for sailing and the Mediterranean.",
    "about.value2.title": "Safety First",
    "about.value2.desc": "All our boats have up-to-date certifications, comprehensive insurance and professional safety equipment.",
    "about.value3.title": "Service Excellence",
    "about.value3.desc": "Our goal is to exceed your expectations in every experience, caring for every detail.",
    "about.value4.title": "Personalized Service",
    "about.value4.desc": "We're not a large corporation. We're a team that accompanies you from booking to disembarkation.",
    "about.certs.title": "Certifications and Licenses",
    "about.certs.subtitle": "Your safety and peace of mind are our priority",
    "about.cert1": "Professional nautical licenses",
    "about.cert2": "Comprehensive insurance",
    "about.cert3": "Seaworthiness certificates",
    "about.cert4": "First aid training",
    "about.cert5": "Certified maintenance",
    "about.certs.footer": "All our captains have professional qualifications and years of experience navigating these waters.",
    "about.testimonials.title": "What Our Clients Say",
    "about.testimonials.subtitle": "Real experiences from people who sailed with us",
    "about.test1.name": "María González",
    "about.test1.location": "Madrid",
    "about.test1.text": "An unforgettable experience. The sunset from the boat was magical and the team was super professional and attentive. Totally recommended!",
    "about.test2.name": "John Smith",
    "about.test2.location": "UK",
    "about.test2.text": "Best boat charter experience in Costa Blanca! Beautiful yacht, amazing crew, and the hidden coves were spectacular. Will definitely return!",
    "about.test3.name": "Carlos Ruiz",
    "about.test3.location": "Valencia",
    "about.test3.text": "We celebrated my birthday on board and it was perfect. The decoration, the food, everything was taken care of in detail. Thank you for making this day so special.",
    "about.cta.title": "Ready for your sea adventure?",
    "about.cta.subtitle": "Join hundreds of satisfied customers who have already lived the Golden Coast experience",
    "about.cta.button": "Request Your Quote",

    // ============= BOOKING PAGE =============
    "booking.heroTitle": "Request Your",
    "booking.heroHighlight": "Quote",
    "booking.heroDesc": "Complete the form and we'll send you a personalized quote. You can also contact us directly via WhatsApp for an immediate response.",
    "booking.form.name": "Full name",
    "booking.form.email": "Email",
    "booking.form.phone": "Phone",
    "booking.form.date": "Preferred date",
    "booking.form.guests": "Number of people",
    "booking.form.guestsPlaceholder": "e.g: 8",
    "booking.form.boatType": "Boat type",
    "booking.form.selectBoat": "Select...",
    "booking.form.experience": "Desired experience",
    "booking.form.message": "Additional message",
    "booking.form.messagePlaceholder": "Tell us more about what you're looking for...",
    "booking.form.submit": "Send Request",
    "booking.form.sending": "Sending...",
    "booking.form.privacy": "By submitting this form you accept our privacy policy",
    "booking.form.namePlaceholder": "Your name",
    "booking.form.emailPlaceholder": "your@email.com",
    "booking.form.phonePlaceholder": "+34 676 26 26 28",
    "booking.boat.motor": "Motor (with captain)",
    "booking.boat.sailWith": "Sail (with captain)",
    "booking.boat.sailWithout": "Sail (without captain)",
    "booking.boat.any": "Any",
    "booking.exp.sunset": "Sunset",
    "booking.exp.party": "Party/Birthday",
    "booking.exp.family": "Family adventure",
    "booking.exp.custom": "Custom",
    "booking.exp.other": "Other",
    "booking.benefits.title": "Why book with us?",
    "booking.benefit1": "Response in less than 24h",
    "booking.benefit2": "No-commitment quote",
    "booking.benefit3": "Personalized advice",
    "booking.benefit4": "Flexible dates",
    "booking.contact.title": "Prefer direct contact?",
    "booking.contact.whatsapp": "Direct WhatsApp",
    "booking.contact.phone": "+34 676 26 26 28",
    "booking.contact.email": "Email",
    "booking.contact.schedule": "Hours: Mon-Sun 9:00-21:00",
    "booking.toast.error.title": "Error",
    "booking.toast.error.desc": "Please complete all required fields",
    "booking.toast.success.title": "Request sent!",
    "booking.toast.success.desc": "We'll contact you in less than 24 hours.",

    // ============= ROUTES PAGE =============
    "routes.heroTitle": "Our",
    "routes.heroHighlight": "Routes",
    "routes.heroDesc": "Discover the most spectacular corners of the Costa Blanca. Each route is a unique adventure designed to experience the Mediterranean at its finest.",
    "routes.route1.name": "Las Rotas & Cabo de San Antonio Marine Reserve",
    "routes.route1.location": "Dénia - Cabo San Antonio",
    "routes.route1.duration": "4-6 hours",
    "routes.route1.desc": "Navigate the stunning coastline of Las Rotas, discovering its hidden caves and snorkeling in the protected waters of the Cabo de San Antonio marine reserve. A journey into nature's heart.",
    "routes.route1.highlight1": "Natural caves",
    "routes.route1.highlight2": "Snorkeling in marine reserve",
    "routes.route1.highlight3": "Crystal-clear waters",
    "routes.route1.highlight4": "Rocky seabeds",
    "routes.route2.name": "The Coves of Jávea (Granadella, Portitxol, Ambolo)",
    "routes.route2.location": "Jávea - Cabo Coast",
    "routes.route2.duration": "5-7 hours",
    "routes.route2.desc": "Explore the most famous coves of Jávea from a unique perspective. Anchor in the turquoise waters of Granadella, admire the blue-domed houses of Portitxol, and feel the magic of Ambolo.",
    "routes.route2.highlight1": "Granadella Cove",
    "routes.route2.highlight2": "Portitxol",
    "routes.route2.highlight3": "Ambolo Cove",
    "routes.route2.highlight4": "Anchoring in pristine coves",
    "routes.route3.name": "Sunset and Montgó Cliffs",
    "routes.route3.location": "Dénia - Montgó",
    "routes.route3.duration": "2-3 hours",
    "routes.route3.desc": "Experience an unforgettable sunset as the sun dips behind the majestic Montgó mountain. A moment of pure magic, perfect for a romantic evening or a peaceful end to the day.",
    "routes.route3.highlight1": "Magical sunset",
    "routes.route3.highlight2": "Montgó views",
    "routes.route3.highlight3": "Romantic moment",
    "routes.route3.highlight4": "Cava included",
    "routes.highlights": "Route highlights:",
    "routes.bookRoute": "Book this Route",
    "routes.cta.title": "Have a route in mind?",
    "routes.cta.desc": "We can customize any itinerary according to your preferences. Whether it's a specific cove, a combination of routes, or a special destination, we design the perfect experience for you.",
    "routes.cta.button": "Create Custom Route",

    // ============= FOOTER =============
    "footer.slogan": "Luxury nautical experiences on the Costa Blanca. Boat rentals in Dénia and Jávea for unforgettable moments.",
    "footer.quickLinks": "Quick Links",
    "footer.experiences": "Experiences",
    "footer.contact": "Contact",
    "footer.email": "Email",
    "footer.phone": "Phone",
    "footer.social": "Follow Us",
    "footer.rights": "All rights reserved",
    "footer.legal.privacy": "Privacy Policy",
    "footer.legal.terms": "Terms & Conditions",
    "footer.legal.cookies": "Cookies",
    "footer.legal.notice": "Legal Notice",
    "footer.exp.sunset": "Sunset Cruises",
    "footer.exp.celebrations": "Celebrations",
    "footer.exp.family": "Family Routes",
    "footer.exp.custom": "Custom Charter",
    "footer.location": "Port of Dénia\nMarina of Jávea\nCosta Blanca, Spain",
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("es");

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'es' || savedLang === 'en')) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.es] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
